# Generated by Django 3.2 on 2021-04-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movement',
            name='banking_mov_fintoc__171387_idx',
        ),
    ]
