# Generated by Django 3.1.7 on 2021-03-27 15:28

import django.contrib.postgres.fields
from django.db import migrations, models
import lottery.models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='pool',
        ),
        migrations.AddField(
            model_name='draw',
            name='pool',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=lottery.models.generate_result_pool, size=None, verbose_name='result pool'),
        ),
        migrations.RemoveField(
            model_name='draw',
            name='results',
        ),
        migrations.AddField(
            model_name='draw',
            name='results',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None, verbose_name='results'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='picks',
        ),
        migrations.AddField(
            model_name='ticket',
            name='picks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=lottery.models.generate_random_picks, size=None),
        ),
    ]
