[metadata]
server = "http://localhost:8000"

# Misc.
[endpoints.error]
route = "/error"
method = "get"

[endpoints.health-check]  # Doesn't really show anything
route = "/"
method = "get"

# Session.
[endpoints.login]
route = "/v1/login"
method = "post"
body = ["email", "password"]

# Users.
[endpoints.create-user]
route = "/v1/users"
method = "post"
body = [
  "email",
  "first_name",
  "last_name",
  { name = "rut", type = "integer" },
  { name = "check_digit", type = "integer" },
  "password"
]

[endpoints.get-user]
route = "/v1/users/{user_id}"
method = "get"
params = ["user_id"]
headers = ["Authorization"]

[endpoints.get-tickets]
route = "/v1/users/{user_id}/tickets?page={page}&page_size={page_size}"
method = "get"
params = ["user_id", "page", "page_size"]
headers = ["Authorization"]

# Draws.
[endpoints.get-ongoing-draw]
route = "/v1/draws/ongoing"
method = "get"
headers = ["Authorization"]

# Internal
[endpoints.create-draw]
route = "/v1/draws"
method = "post"
headers = ["Internal-Key"]

[endpoints.choose-result]
route = "/v1/draws/ongoing/choose"
method = "post"
headers = ["Internal-Key"]

[endpoints.fetch-movements]
route = "/v1/movements/fetch"
method = "post"
headers = ["Internal-Key"]
