# Generated by Django 3.2 on 2021-04-17 17:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import main.base


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_use_arrayfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated at')),
                ('android_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='Android ID')),
                ('ios_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='iOS ID')),
                ('expo_push_token', models.CharField(max_length=255, null=True, unique=True, verbose_name='Expo push token')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(check=main.base.ExtendedQ(main.base.ExtendedQ(('android_id__isnull', False), main.base.ExtendedQ(_negated=True, ios_id__isnull=False)), main.base.ExtendedQ(main.base.ExtendedQ(_negated=True, android_id__isnull=False), ('ios_id__isnull', False)), _connector='OR'), name='exactly_one_os_id'),
        ),
    ]
