# Generated by Django 3.2 on 2021-04-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_rut_a2654b_idx',
        ),
    ]
