name: checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up testing environment
        run: |
          make localsettings
          docker-compose build --parallel
          docker-compose up --detach
          docker-compose down

      - name: Run unit tests
        run: make test
