name: production

on:
  push:
    branches:
      - stable

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION_NAME }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_PRODUCTION_ENVIRONMENT_NAME }}
          version_label: ${{ secrets.EB_PRODUCTION_VERSION_LABEL }}
