name: tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up testing environment
        run: make localsettings

      - name: Build Docker images
        run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build --parallel

      - name: Test running functionality
        run: |
          docker-compose up --detach
          docker-compose down

      - name: Run unit tests
        run: make test
